version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  reviewers:
  - Molizo
  assignees:
  - Molizo
  ignore:
  - dependency-name: Sentry
    versions:
    - 3.0.0
    - 3.0.1
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.0.5
    - 3.0.6
    - 3.0.7
    - 3.0.8
    - 3.1.0
    - 3.2.0
    - 3.3.0
    - 3.3.1
    - 3.3.2
  - dependency-name: Sentry.AspNetCore
    versions:
    - 3.0.0
    - 3.0.1
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.0.5
    - 3.0.6
    - 3.0.7
    - 3.0.8
    - 3.1.0
    - 3.2.0
    - 3.3.0
    - 3.3.1
    - 3.3.2
  - dependency-name: SendGrid
    versions:
    - 9.22.0
  - dependency-name: Microsoft.VisualStudio.Web.CodeGeneration.Design
    versions:
    - 5.0.1
- package-ecosystem: npm
  directory: "/SkystoneScouting"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  reviewers:
  - Molizo
  assignees:
  - Molizo
  ignore:
  - dependency-name: nouislider
    versions:
    - 14.6.3
    - 14.6.4
  - dependency-name: dropzone
    versions:
    - 5.7.2
    - 5.7.4
    - 5.7.5
    - 5.7.6
    - 5.8.0
    - 5.8.1
  - dependency-name: lodash
    versions:
    - 4.17.20
