version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: x64
nuget:
  account_feed: true
  project_feed: true
build:
  publish_wap: true
  publish_aspnet_core: true
  parallel: true
  verbosity: detailed
